name: OctoPetShop Pre-Release

on:
  workflow_dispatch:

jobs:

  build:
    
    name: builds docker image
    runs-on: ubuntu-latest
    
    outputs:
      version: ${{ steps.version-generator.outputs.version }}
      
    steps:
    
     - uses: actions/checkout@v3
    
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
        username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
        
     - name: Set Version Number

       id: version-generator
       run: echo "version=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

     - name: Build OctoPetShop web container
       run: |
        docker build ./OctopusSamples.OctoPetShop.Web --file ./OctopusSamples.OctoPetShop.Web/dockerfile --tag octopussamples/octopetshop-web-enterprise:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-web-enterprise:$PACKAGE_VERSION
        
     - name: Build OctoPetShop product service container
       run: | 
        docker build ./OctopusSamples.OctoPetShop.ProductService --file ./OctopusSamples.OctoPetShop.ProductService/dockerfile --tag octopussamples/octopetshop-productservice-enterprise:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-productservice-enterprise:$PACKAGE_VERSION
        
     - name: Build OctoPetShop shopping cart container
       run: | 
        docker build ./OctopusSamples.OctoPetShop.ShoppingCartService --file ./OctopusSamples.OctoPetShop.ShoppingCartService/dockerfile --tag octopussamples/octopetshop-shoppingcartservice-enterprise:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-shoppingcartservice-enterprise:$PACKAGE_VERSION
        
     - name: Build OctoPetShop database container
       run: | 
        docker build ./OctopusSamples.OctoPetShop.Database --file ./OctopusSamples.OctoPetShop.Database/dockerfile --tag octopussamples/octopetshop-database-enterprise:$PACKAGE_VERSION
        docker push octopussamples/octopetshop-database-enterprise:$PACKAGE_VERSION
        
        
  Push-build-information:
       
      name: Push Build Information üêô
      needs: build 
      runs-on: ubuntu-latest
      
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE }}
      

      steps:
      - uses: OctopusDeploy/push-build-information-action@v3
        name: Push Build Information
        with:
          version: ${{ needs.build.outputs.version }}
          packages: |
            octopussamples/octopetshop-web-enterprise
            octopussamples/octopetshop-productservice-enterprise
            octopussamples/octopetshop-shoppingcartservice-enterprise
            octopussamples/octopetshop-database-enterprise
          
  Create-Octopus-Release:
  
      name: Create Octopus Release üêô
      needs: [build, Push-build-information]
      runs-on: ubuntu-latest
      
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE }}
        
      steps:
      - uses: OctopusDeploy/create-release-action@v3
        id: "create-release"
        with:
          project: OctoPetShop
          git_ref: main
      outputs: 
       release_number: ${{ steps.create-release.outputs.release_number }}
          
          
          
            
            

        

      
        
        
      
      
             
         
  
        

      
   
