name: Release workflow

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      #- uses: ncipollo/release-action@v1
       - name: Create GitHub release
         run: echo "creating release"

  promote-artifact:
    name: Promote artifact ğŸ”¼
    runs-on: ubuntu-latest
    needs: create-github-release

    steps:
      - name: Promote artifact
        run: echo "Promoting artifact âœ…"

  deploy-octopus-release:
    name: Deploy Octopus release ğŸ™
    runs-on: ubuntu-latest
    needs: promote-artifact
      
    env:
      OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE_NAME }}

    steps:
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.6
        with:
          version: latest

      - name: promote release
        run: octo promote-release --project "OctoPetShop - Gitflow 2" --from Development --to Test --progress --server ${{ secrets.OCTOPUS_SERVER_URL }} --apikey ${{ secrets.OCTOPUS_API_KEY }} --space "${{ secrets.OCTOPUS_SPACE_NAME }}"

  manual-test-suite:
    name: Run manual test suite ğŸ§ª
    runs-on: ubuntu-latest
    needs: deploy-octopus-release
    environment: 'Hom'
                
    steps:
      - name: Run manual test suite
        run: echo "Executing manual test suite âœ…"

  automated-test-suite:
    name: Run automated test suite ğŸ§ª
    runs-on: ubuntu-latest
    needs: deploy-octopus-release
    
    steps:
      - name: Run automated test suite
        run: echo "Executing automated test suite âœ…"

  approval:
    name: Approve deployment âœ…
    needs: [manual-test-suite, automated-test-suite]
    runs-on: ubuntu-latest
    environment: 'Hom'
      
    steps:
      - name: Gather approval
        run: echo "Approval gathered âœ…"